# ===============================
# APPLICATION
# ===============================
spring.application.name=BOOKING-SERVICE
server.port=${BOOKING_SERVICE_PORT:8083}

# ===============================
# MYSQL DATABASE
# ===============================
spring.datasource.url=${BOOKING_DB_URL:jdbc:mysql://localhost:3306/starlight_booking_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${BOOKING_DB_USERNAME:root}
spring.datasource.password=${BOOKING_DB_PASSWORD:1234}

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# EUREKA
# ===============================
eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ===============================
# LOGGING
# ===============================
logging.level.com.starlight.booking=INFO
# ===============================
# JWT
# ==============================
jwt.secret=${JWT_SECRET:starlight-hospitality-secret-key-must-be-at-least-32-characters-long}
