package com.starlight.gateway.error;

import org.springframework.boot.web.error.ErrorAttributeOptions;
import org.springframework.boot.web.reactive.error.DefaultErrorAttributes;
import org.springframework.stereotype.Component;
import org.springframework.web.reactive.function.server.ServerRequest;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.LinkedHashMap;
import java.util.Map;

/** Produces a consistent JSON envelope for errors generated by the Gateway. */
@Component
public class GatewayErrorAttributes extends DefaultErrorAttributes {

    private static final DateTimeFormatter TIMESTAMP_FORMAT =
            DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss");

    @Override
    public Map<String, Object> getErrorAttributes(ServerRequest request, ErrorAttributeOptions options) {
        Map<String, Object> defaults = super.getErrorAttributes(request, options);
        int status = toInt(defaults.get("status"), 500);
        String reason = String.valueOf(defaults.getOrDefault("error", "Internal Server Error"));

        Map<String, Object> body = new LinkedHashMap<>();
        body.put("timestamp", LocalDateTime.now().format(TIMESTAMP_FORMAT));
        body.put("status", status);
        body.put("error", reason);
        body.put("errorCode", toErrorCode(status));
        body.put("message", defaultMessageFor(status));
        body.put("path", String.valueOf(defaults.getOrDefault("path", request.path())));
        return body;
    }

    private int toInt(Object value, int fallback) {
        return value instanceof Number number ? number.intValue() : fallback;
    }

    private String toErrorCode(int status) {
        return switch (status) {
            case 400 -> "BAD_REQUEST";
            case 401 -> "UNAUTHORIZED";
            case 403 -> "FORBIDDEN";
            case 404 -> "RESOURCE_NOT_FOUND";
            case 409 -> "CONFLICT";
            case 503 -> "SERVICE_UNAVAILABLE";
            default -> "INTERNAL_SERVER_ERROR";
        };
    }

    private String defaultMessageFor(int status) {
        return switch (status) {
            case 400 -> "The request was malformed or contained invalid parameters.";
            case 401 -> "Authentication is required to access this resource.";
            case 403 -> "You do not have permission to perform this operation.";
            case 404 -> "No route or resource matched the requested path.";
            case 409 -> "The request conflicts with the current state of the resource.";
            case 503 -> "The requested service is currently unavailable. Please try again later.";
            default -> "An unexpected error occurred while processing the request.";
        };
    }
}
